server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jacQUE656/muse_microservice_backend.git
          clone-on-start: true
          default-label: main

          # 📂 Exact relative path from the repository root to your config files
          search-paths: services/config-service/config