services:
  postgres:
    image: postgres:14
    container_name: muse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: muse
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - muse-net

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - muse-net

  config-server:
    image: jacque56/muse-config:v1
    container_name: config-service
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - muse-net

  eureka-server:
    image: jacque56/muse_eurekaserver:v1
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - muse-net

  gateway-service:
    image: jacque56/muse_gateway_server:v1
    container_name: gateway-server
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      SERVER_PORT: 7000
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server
    networks:
      - muse-net

  album-service:
    image: jacque56/muse-album:v1
    container_name: album-service
    restart: unless-stopped
    ports:
      - "10001:10001"
    environment:
      SERVER_PORT: 10001
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      ALBUM_DB: muse_album_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - postgres
      - config-server
      - eureka-server
      - kafka
      - gateway-service
    networks:
      - muse-net

  song-service:
    image: jacque56/muse-song:v1
    container_name: song-service
    restart: unless-stopped
    ports:
      - "10003:10003"
    environment:
      SERVER_PORT: 10003
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      SONG_DB: muse_song_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - config-server
      - eureka-server
      - kafka
      - gateway-service
    networks:
      - muse-net

  user-service:
    image: jacque56/muse-user:v1
    container_name: user-service
    restart: unless-stopped
    ports:
      - "10002:10002"
    environment:
      SERVER_PORT: 10002
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      USER_DB: muse_user
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - config-server
      - eureka-server
      - kafka
      - gateway-service
    networks:
      - muse-net

  playlist-service:
    image: jacque56/muse-playlist:v1
    container_name: playlist-service
    restart: unless-stopped
    ports:
      - "10004:10004"
    environment:
      SERVER_PORT: 10004
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      PLAYLIST_DB: muse_playlist_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - config-server
      - eureka-server
      - kafka
      - gateway-service
    networks:
      - muse-net

  notification-service:
    image: jacque56/muse-notification:v1
    container_name: notification-server
    restart: unless-stopped
    ports:
      - "10005:10005"
    environment:
      SERVER_PORT: 10005
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      NOTIFICATION_DB: muse_notification_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - config-server
      - eureka-server
      - kafka
      - gateway-service
    networks:
      - muse-net

  payment-service:
    image: jacque56/muse-payment:v1
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "10006:10006"
    environment:
      SERVER_PORT: 10006
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      PAYMENT_DB: muse_payment_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - config-server
      - eureka-server
      - kafka
      - gateway-service
    networks:
      - muse-net

networks:
  muse-net:
    driver: bridge

volumes:
  pgdata:
  kafka-data: