eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Shared Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# Shared JWT Configuration
jwt:
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000

# Shared JPA Configuration
spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        spring.json.add.type.headers: false

# Shared Logging Configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG

razorpay:
  api:
    key: rzp_test_a9B8cD7eF6gH1i
    secrete: QwErTyUiOpAsDfGhHjKlZxCv
stripe:
  api:
    key: sk_test_51P8zW2kL9mNxO4pQ7rS5tU3vW1xY0zABcDeFgHiJkLmNoPqRsTuVwXyZ
