server:
  port: 7000

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: &standardRoles USER,ADMIN,PREMIUM_USER

            - id: AUTH-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: USER-SERVICE-ADMIN
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/admin/users/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: ADMIN

            - id: ALBUM-SERVICE-ADMIN
              uri: lb://ALBUM-SERVICE
              predicates:
                - Path=/api/admin/albums/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: ADMIN

            - id: ALBUM-SERVICE-PREMIUM
              uri: lb://ALBUM-SERVICE
              predicates:
                - Path=/api/premium/albums/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: PREMIUM_USER

            - id: ALBUM-SERVICE-USER
              uri: lb://ALBUM-SERVICE
              predicates:
                - Path=/api/albums/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: *standardRoles

            - id: SONG-SERVICE-USER
              uri: lb://SONG-SERVICE
              predicates:
                - Path=/api/songs/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: *standardRoles

            - id: SONG-SERVICE-ADMIN
              uri: lb://SONG-SERVICE
              predicates:
                - Path=/api/admin/songs/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: ADMIN

            - id: SONG-SERVICE-PREMIUM
              uri: lb://SONG-SERVICE
              predicates:
                - Path=/api/premium/songs/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: PREMIUM_USER,ADMIN

            - id: PLAYLIST-SERVICE-ADMIN
              uri: lb://PLAYLIST-SERVICE
              predicates:
                - Path=/api/admin/playlists/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: ADMIN

            - id: PLAYLIST-SERVICE-PREMIUM
              uri: lb://PLAYLIST-SERVICE
              predicates:
                - Path=/api/premium/playlists/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: PREMIUM_USER

            - id: PLAYLIST-SERVICE-USER
              uri: lb://PLAYLIST-SERVICE
              predicates:
                - Path=/api/playlists/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: *standardRoles

            - id: NOTIFICATION-SERVER
              uri: lb://NOTIFICATION-SERVER
              predicates:
                - Path=/api/notifications/**
              filters:
                - name: GatewayAuthFilter
                  args:
                    allowedRoles: *standardRoles

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      httpclient:
        connect-timeout: 3000
        response-timeout: 10s