server:
  port: 10006

spring:
  datasource:
    url: jdbc:postgresql://muse-postgres:5432/${PLAYLIST_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
