server:
  port: 1004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${PAYMENT_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver