server:
  port: 10002

spring:
  application:
    name: user-service

  datasource:
    # 🔌 Appended auto-create flag and environmental safety fallbacks
    url: jdbc:postgresql://localhost:5432/${USER_DB}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: corg.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy_secret}
            scope:
              - profile
              - email

# 📧 Structured as a clean list for effortless @ConfigurationProperties binding
disposable:
  emails:
    - 10minutemail
    - 20minutemail
    - 33mail
    - 5ymail
    - anonbox
    - mailinator
    - mailnesia
    - throwawaymail
    - yopmail
    - trashmail
    - temp-mail
    - tempmail
    - moakt
    - guerrillamail